Bluewire repo analysis tools
BluewireTechnologies/canarybuilder pull request #2
Opened 2017-03-10 11:44 UTC by alex-davidson

Implements the Bluewire.Tools.Runner tool host application, initially with only two children:
* `find-build`
* `generate-scripts`

2017-03-10 12:31 UTC, luckyrat commented on Bluewire.Tools.GitRepository.IntegrationTests/BranchIntegrationPointLocatorTests.cs
> +        public async Task SubjectAtTipOfBranchMergedImmediatelyAfterStartResolvesToIdentityOfMergeCommitImmediatelyFollowingStart()
Some of these mentions of "After start" and "Following start" are confusing me. Are they the same thing? If not, is there some alternative terminology we could use for one of them?

2017-03-10 12:33 UTC, alex-davidson commented on Bluewire.Tools.GitRepository.IntegrationTests/BranchIntegrationPointLocatorTests.cs
> +        public async Task SubjectAtTipOfBranchMergedImmediatelyAfterStartResolvesToIdentityOfMergeCommitImmediatelyFollowingStart()
I can't remember. I think there was a reason but it eludes me.

2017-03-10 12:35 UTC, alex-davidson commented on Bluewire.Tools.GitRepository.IntegrationTests/BranchIntegrationPointLocatorTests.cs
> +        public async Task SubjectAtTipOfBranchMergedImmediatelyAfterStartResolvesToIdentityOfMergeCommitImmediatelyFollowingStart()
I think it has something to do with multiple commits capable of being 'after' the start commit, but only one can 'follow' it on the first-parent ancestry chain. Or something.

2017-03-16 12:20 UTC, luckyrat requested changes
Looks great apart from those few issues I've mentioned, mostly minor whitespace stuff. If you could look into the naming of those tests too that would be good. Maybe once you've understood their purpose, we can brainstorm a clearer name for them.

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Tools.GitRepository.IntegrationTests/TopologicalBuildNumberResolverTests.cs
> +
Too many blank lines.

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Tools.GitRepository/TopologicalBuildNumberCalculator.cs
> +            if(!int.TryParse(line, out buildNumber)) return null;
Missing space after if keyword.

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Tools.GitRepository/TopologicalBuildNumberResolver.cs
> +            var target =  await SearchImplementation.Search(candidatesDescending, buildNumber, r => calculator.GetBuildNumber(workingCopyOrRepo, start, r));
extra space after =

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Conventions/BranchSemantics.cs
> +            if(lastNamespacePart == null) return BranchType.None;
missing space after `if`

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Conventions/SprintNumber.cs
> +            if(version.Revision < 0 && version.Build < 0) return version;
Missing space after `if`

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Tools.Runner/FindBuild/RepositoryStructureInspector.cs
> +            if (recognisedBranches.Length <= pruneThreshold) return recognisedBranches;
Looks like we only need one of the above conditionals. Maybe put a check at the top of the function to ensure pruneThreshold is always >= 1 instead?

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Tools.Runner/FindBuild/ResolveBuildVersionsFromGitHubPullRequest.cs
> +            var mergedCommits = prMerges.Select(m => m.MergeParents?.Skip(1)).Aggregate((rs, r) => r == null ? Enumerable.Empty<Ref>() : rs.Intersect(r)).ToArray();
This `Skip(1)` is potentially a little opaque so perhaps include a quick comment to explain it's related to the git merge parent conventions/specification?

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Tools.Runner/FindBuild/ResolveBuildVersionsFromTicketIdentifier.cs
> +            // But --is-ancestor is rather expensive too, especially for an O(n^2) operation...
This confused me a bit. I think you're talking about the implementation details of some of the methods that are called by this method but I'm not sure exactly how it relates to this particular method. Is it essentially aiming to explain why we are calling `IsChildOfAny` on each hash? It looks like that calls `--is-ancestor` so I'm not sure what to make of the comment that says this operation is expensive. I assume it's been found to be faster than not culling the list of hashes at all?

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Tools.Runner/FindBuild/TargetBranchResolver.cs
> +            var inspector = new RepositoryStructureInspector(gitSession);
Do we need to create this object every time we call this method? It looks like it is tied to the `gitSession` which is not going to change so why not make this an instance property and lazily instantiate the backing field instead? Alternatively, if there is some state within the inspector that we want to discard every time we invoke `IdentifyTargetBranchesOfCommit`, perhaps making the inspector disposable and wrapping its use in a using block would make this more explicit.

2017-03-16 12:20 UTC, luckyrat commented on Bluewire.Tools.Runner/GenerateScripts/ToolRunner.cs
> +";
There are some weird line endings in the strings returned from this and the above method. Is that intentional? If so, why are only 3 of the 4 line endings represented in that way?

2017-03-16 12:49 UTC, alex-davidson commented on Bluewire.Tools.Runner/FindBuild/TargetBranchResolver.cs
> +            var inspector = new RepositoryStructureInspector(gitSession);
It's a service object. It doesn't store any state and merely encapsulates logic. There's no particular need to keep it around between calls.

2017-03-16 13:01 UTC, alex-davidson commented on Bluewire.Tools.Runner/FindBuild/RepositoryStructureInspector.cs
> +            if (recognisedBranches.Length <= pruneThreshold) return recognisedBranches;
I'll reorder the conditionals to make it clearer why I did it like this.

2017-03-16 13:09 UTC, alex-davidson commented on Bluewire.Tools.Runner/GenerateScripts/ToolRunner.cs
> +";
This is a GitHub rendering artifact. Examining the file shows that all line breaks are CRLF.

2017-03-16 13:41 UTC, alex-davidson commented
Test failure on TeamCity.

2017-03-16 14:04 UTC, luckyrat approved these changes

2017-03-16 14:04 UTC, merged